#
# Serverless configuration reference:
#
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
#
service: hello-http

provider:
  name: aws
  region: us-east-1
  runtime: python3.7

functions:
  helloPath:
    handler: handler.helloPath
    events:
      - http:
          # TODO Change to use path parameter
          # DONE
          path: hello/{pathParam}
          method: get
          request:
            parameters:
              paths:
                pathParam: true
  helloQuery:
    handler: handler.helloQuery
    events:
      - http:
          path: helloq
          method: get
  helloPost:
    handler: handler.helloPost
    events:
      - http:
          path: hello_post
          method: post                
  # TODO Set up the new function here to handle HTTP POST event

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      # Comment out if you want to deploy to AWS instead of LocalStack
      - dev
